### ISSUE TITLE
Support for converting IPv6 to Text

### ISSUE THREAD

**Issue by Porges** [andrewthad/haskell-ip#11]
IPv4 has `encode :: IPv4 -> Text`, but the corresponding function doesn't exist for IPv6

**Comment by andrewthad** [comment]
This look good. Thanks for writing tests too. Performance won't be great (to get the best performance, you'd have to allocate a buffer unfront and then do writes indexing the appropriate positions), but it's much better to have something slow than nothing ;)

**Comment by andrewthad** [comment]
PR has been merged. New hackage realease `0.9.2` includes this and the parser fix.

**Comment by Porges** [comment]
Thanks!
