### ISSUE TITLE
Support 'mixed' IPv6 representations

### ISSUE THREAD

**Issue by Porges** [andrewthad/haskell-ip#12]
[RFC4291 specifies a "mixed" IPv6 syntax](https://tools.ietf.org/html/rfc4291#page-4) that is not currently supported:

> 3. An alternative form that is sometimes more convenient when dealing
>      with a mixed environment of IPv4 and IPv6 nodes is
>      `x:x:x:x:x:x:d.d.d.d`, where the '`x`'s are the hexadecimal values of
>      the six high-order 16-bit pieces of the address, and the '`d`'s are
>      the decimal values of the four low-order 8-bit pieces of the
>      address (standard IPv4 representation).  Examples:
>
>         `0:0:0:0:0:0:13.1.68.3`
>
>         `0:0:0:0:0:FFFF:129.144.52.38`
>
>      or in compressed form:
>
>         `::13.1.68.3`
>
>         `::FFFF:129.144.52.38`

**Comment by andrewthad** [comment]
I would gladly take a PR adding support for this.
