### ISSUE TITLE
Parser hang on invalid input

### ISSUE THREAD

**Issue by Porges** [andrewthad/haskell-ip#14]
The following hangs rather than succeeding or failing:

    parseOnly Net.IPv6.Text.parser "1111:2222:3333:4444:5555:6666::7777:8888"

Forcing just to `Left` or `Right` also fails:

    either (const "L") (const "R") $ parseOnly Net.IPv6.Text.parser "1111:2222:3333:4444:5555:6666::7777:8888"

**Comment by Porges** [comment]
Actually, the parse itself is fine, producing `Right`, but forcing the parse result hangs.

**Comment by andrewthad** [comment]
Sorry, I just realized that I wasn't previously receiving notifications for this repo. I'll add a test case for this and figure out what's wrong.
