### ISSUE TITLE
Strange Show/Read instances for IPv4

### ISSUE THREAD

**Issue by chessai** [andrewthad/haskell-ip#24]
I believe it would make more sense for the Show instance for IPv4 to be the following:

```Haskell
instance Show IPv4 where
  showsPrec p addr = showParen (p > 10)
    $ showsPrec 11 a
    . showChar '.'
    . showsPrec 11 b
    . showChar '.'
    . showsPrec 11 c
    . showChar '.'
    . showsPrec 11 d
    where
    (a,b,c,d) = toOctets addr
```

So, the IPv4 address XX.XX.XX.XX would show as "XX.XX.XX.XX", instead of "ipv4 XX XX XX XX"

The strangeness of the Read instance follows from this reasoning.

If you think this is a good idea, I can make a PR. Otherwise, please explain why you do not think it is a good idea.

**Comment by chessai** [comment]
The same goes for IPv6.

**Comment by andrewthad** [comment]
The reason that I wrote them this where is that  a show instance should generate valid haskell code. This isn’t exactly a law, but derived show instances clauses always generate valid haskell code, and every type in base, containers, unordered-containers, text, and bytestring follows this rule. So, I try to play along.  This means that if someone writes a data type with an IPv4 field  and derives a show instance for it, this show instance will produce valid haskell code. This is handy for playing around in GHCi. (The way I see it, using show outside of GHCi is generally not a good idea).  Originally, the instances  originally, the instances  for all the types in this package were just the derived instances,  but those were unreadable for humans, so I ended up changing them to their current form. It is an attempt to strike a balance between readability and being haskell code.

 There is some precedent for using a smart constructor forward the show instance like this. In older versions of text and vector, the instances work like this:

    pack “foo”
    fromList [1,2,3]

But with the introduction of OverloadedStrings and OverloadedLists,  these instances were changed to their current, simpler forms.

**Comment by chessai** [comment]
That is understandable.

Perhaps it would be enough to provide print functions that are not bound by precedent?

**Comment by andrewthad** [comment]
What does "print functions that are not bound by precedent" mean?

    module Net.IPv4 ( ... ) where
    
    print :: IPv4 -> IO ()
    print = ...

Is that what you are describing?

**Comment by chessai** [comment]
Yes.

**Comment by andrewthad** [comment]
Yeah, that sounds fine. I'll take a PR that provide a print function in each module as:

    print :: TheType -> IO ()
    print = Data.Text.IO.putStrLn . encode
