### ISSUE TITLE
Redo Mac Show instance

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/haskell-ip#28]
Consider doing this:

    mac 0xAB 0xCD 0x2C 0xD5 0x79 0x83

Instead of this:

    mac 0xABCD2CD57983

**Comment by chessai** [comment]
Why not just do a similar thing with parsing, where a simple ADT encodes how to print the MAC, and leave the show instance alone? I guess you could do anything with the show instance in addition to the ADT thing

**Comment by andrewthad** [comment]
I'll probably leave this `Show` instance alone. Someone had found it a little confusing (since mac addresses are usually broken into 6 octets), but I don't think it's actually that confusing.
