### ISSUE TITLE
Allow testing with quickcheck-classes-0.4.1

### ISSUE THREAD

**Issue by DanBurton** [andrewthad/haskell-ip#33]
This constraint prevents the test suite from being built on the Stackage build server.

https://github.com/andrewthad/haskell-ip/blob/d2871c6f773636d17b47189ce72c127915e599bd/ip.cabal#L73

**Comment by andrewthad** [comment]
The constraint has been lifted. Also, I've push out a new release that builds with GHC 8.4.1.

**Comment by DanBurton** [comment]
Cool, thanks. I should have mentioned that you can also relax the constraint on `hspec` to allow for `hspec-2.5.0`.

https://github.com/andrewthad/haskell-ip/blob/0a9d76d491ad814109b230f9eb38d1c85c795127/ip.cabal#L96

**Comment by chessai** [comment]
Can this be closed?

**Comment by andrewthad** [comment]
I've just now lifted the restriction on `hspec`. I don't usually put upper bounds on test suites, so I don't know how that ended up there.
