### ISSUE TITLE
Doesn't building with base-4.7

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/haskell-ip#4]
This package does not build with base-4.7. There's no reason that it couldn't. Someone just needs to add imports to the appropriate module (like importing `Control.Applicative` in various places). I'll happily accept a PR to fix this if someone needs this to work with GHC 7.8.

**Comment by andrewthad** [comment]
Also, if someone does do this, don't use CPP.

**Comment by chessai** [comment]
Do you still want to support GHC <8.0?

**Comment by andrewthad** [comment]
Not really. Closing.
