### ISSUE TITLE
doctests don't parse CPP

### ISSUE THREAD

**Issue by chessai** [andrewthad/haskell-ip#44]
Test suite doctest: RUNNING...

src/Net/IPv4.hs:441:0: error:
     error: missing binary operator before token "("
     #if MIN_VERSION_aeson(1,0,0)
     
    |
441 | #if MIN_VERSION_aeson(1,0,0)
    | ^
doctest: `cc' failed in phase `C pre-processor'. (Exit code: 1)
Test suite doctest: FAIL

**Comment by chessai** [comment]
i am unfamiliar with using doctests. i do not know why this happens or if it is fixable. i have disabled our doctests for now.

**Comment by Porges** [comment]
You just need to add `"-XCPP"` to the list of doctest arguments.

**Comment by chessai** [comment]
> You just need to add `"-XCPP"` to the list of doctest arguments.

This worked, thanks!
