### ISSUE TITLE
New release to Hackage?

### ISSUE THREAD

**Issue by dhess** [andrewthad/haskell-ip#53]
Any chance of getting a new release to Hackage, with the IPv6 support?

**Comment by chessai** [comment]
What IPv6 support are you referring to?

**Comment by dhess** [comment]
Sorry, I should have said, the new IPv6 implementation. (I’d forgotten that it existed before I contributed 0742cd48f5a49a0e8718f6eb559c70d5192ac799)

**Comment by chessai** [comment]
It's already on hackage, no? http://hackage.haskell.org/package/ip-1.5.0/docs/Net-Types.html#t:IPv6

**Comment by dhess** [comment]
Sorry, it appears you're correct!
