### ISSUE TITLE
Why IPv4 does not derive Integral?

### ISSUE THREAD

**Issue by masakifk** [andrewthad/haskell-ip#56]
IPv6 is deriving Integral and it is very useful for address computation.

But IPv4 does not derive Integral.  If IPv4 also derives Integral, it's very useful.

**Comment by chessai** [comment]
Ive never actually needed the num or integral instances for these types. Why are they useful? What does it mean to add two ip addresses? What does it mean to perform integral division on ip addresses?

To me, these instances should probably be removed, rather than added.

**Comment by andrewthad** [comment]
In https://github.com/andrewthad/haskell-ip/pull/58, the `Integral` instance for `IPv6` has been removed. The bad thing about a `Num` instance for `IPv4` (or `IPv6`) is that it makes it possible for the compiler to accept code with numeric literal in the wrong place. It's also not clear to me which method of `Integral` would be useful for `IPv4` addresses. I'm closing this issue, but if you'd like to open another explaining the utility you find in `div` or `mod` that isn't covered by combinators in this library, I'm willing to try to come up with some monomorphic combinators that offer the same convenience.
