### ISSUE TITLE
Bit-order as Bits instance are different in IPv4 and IPv6.

### ISSUE THREAD

**Issue by masakifk** [andrewthad/haskell-ip#57]
When testBit as instance of Data.Bits.Bits, IPv4 and IPv6 behaves differently in ip-1.5.1.
The 0-th bit of IPv4 is the most significant bit.
The 0-th bit of IPv6 is the least significant bit.

> Prelude Data.Bits Net.IPv4 Net.IPv6> testBit (ipv4 0xff 0 0 0) 0
True
Prelude Data.Bits Net.IPv4 Net.IPv6> testBit (ipv4 0xff 0 0 0) 31
False
Prelude Data.Bits Net.IPv4 Net.IPv6> testBit (ipv6 0xffff 0 0 0 0 0 0 0) 0
False
Prelude Data.Bits Net.IPv4 Net.IPv6> testBit (ipv6 0xffff 0 0 0 0 0 0 0) 127
True

Is this expected behavior? Or is it a bug?
If bug, which one is correct behavior?

**Comment by chessai** [comment]
I think this is a bug, since we want network order here. Perhaps this was introduced when switching to wide-word?

**Comment by andrewthad** [comment]
This IPv4 behavior was introduced by https://github.com/andrewthad/haskell-ip/pull/32.

I'm inclined to switch it back to the derived instance.

**Comment by andrewthad** [comment]
Before releasing 1.7.0, this should happen.

**Comment by chessai** [comment]
Why switch it to the derived instance? Shouldn't it be always network-order?

**Comment by chessai** [comment]
if https://github.com/andrewthad/byte-order/pull/4 is merged, this will be really easy to make it network order for both IPv4 and IPv6

**Comment by chessai** [comment]
hmm, actually, we'd need a `Bytes` instance for Word128! probably not hard though.

**Comment by chessai** [comment]
actually that doesnt matter, i just switched to using `toBigEndian`. resolved in aa9f4b2
