### ISSUE TITLE
Please upload to Hackage

### ISSUE THREAD

**Issue by neilmayhew** [andrewthad/haskell-ip#65]
Nix needs the fix for the doctest failures

**Comment by chessai** [comment]
@andrewthad are you currently in the middle of anything which would block a release?

**Comment by andrewthad** [comment]
There’s nothing else I’ve got pending. It’s fine to do a release. It just needs a patch release version bump and a change log mentions.

**Comment by chessai** [comment]
Released as 1.7.2.
