### ISSUE TITLE
aeson-1.5.0.0 is out of bounds for ip

### ISSUE THREAD

**Issue by debug-ito** [andrewthad/haskell-ip#66]
aeson-1.5.0.0 is released, but ip doesn't support it.

**Comment by chessai** [comment]
revision 1 published for ip-1.7.1: https://hackage.haskell.org/package/ip-1.7.1/revisions/

**Comment by chessai** [comment]
commit on github: https://github.com/andrewthad/haskell-ip/commit/ac478d00e7e1da74944707bca81227e7ca233dd3
